on:
  push:
    branches:
      - main
name: ğŸš€ Deploy Website To Cpanel
jobs:
  web-deploy:
    name: ğŸ‰ Deploy To Cpanel
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.codebuilderpro.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
